server:

port: 8881

spring:

datasource:

url: jdbc:mysql://localhost 3386/userderverTimezone UTC&atio@creymescrevai

username: Inventory

password: inventory123

ortver-class-name: com.mysql.cj.japc Driver

1e Ine:

11

12

36

17

18 co

hibernate.

edl-aute: update

show-rgi: False

properties:

hibernate:

dialect: org.hibernate.pialect.MySQLDialect

allowed-origins: http://localhost:3000
